export const PLAYER_TABLET_CHARACTER_NAME_MAX_LENGTH = 32;
export const PLAYER_TABLET_PARAMETER_MIN_VALUE = 0;
export const PLAYER_TABLET_HEALTH_ATTRIBUTE_KEY = 'constitution';
export const PLAYER_TABLET_ATTRIBUTE_MIN_VALUE = 1;
export const PLAYER_TABLET_ATTRIBUTE_MAX_VALUE = 6;
export const PLAYER_TABLET_HEALTH_MULTIPLIER = 5;
export const PLAYER_TABLET_INSPIRATION_MAX_VALUE = 6;
export const PLAYER_TABLET_STRESS_MAX_VALUE = 6;

export const PLAYER_TABLET_PORTRAIT_UPDATE_COOLDOWN_MS = 3 * 60 * 1000;
export const PLAYER_TABLET_PORTRAIT_COOLDOWN_NOTICE_MS = 4 * 1000;
export const PLAYER_TABLET_PORTRAIT_STORAGE_BUCKET = 'temporary-avatars';
export const PLAYER_TABLET_PORTRAIT_STORAGE_FOLDER = 'in-game-character-portraits';
export const PLAYER_TABLET_PORTRAIT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;
export const PLAYER_TABLET_PORTRAIT_ALLOWED_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
];
