import { GameParticipant } from './types';

export const mockMaster: GameParticipant = {
  id: 'master-1',
  userId: 'master-user-1',
  role: 'master',
  displayName: 'Game Master',
  avatarUrl: null,
  joinedAt: '2026-06-07T10:00:00.000Z',
  connectionStatus: 'online',
};

export const mockPlayers: GameParticipant[] = [
  {
    id: 'player-1',
    userId: 'player-user-1',
    role: 'player',
    displayName: 'Daniil',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:01:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-2',
    userId: 'player-user-2',
    role: 'player',
    displayName: 'Yevhenii',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:02:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-3',
    userId: 'player-user-3',
    role: 'player',
    displayName: 'Mira',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:03:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-4',
    userId: 'player-user-4',
    role: 'player',
    displayName: 'Rin',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:04:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-5',
    userId: 'player-user-5',
    role: 'player',
    displayName: 'Kael',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:05:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-6',
    userId: 'player-user-6',
    role: 'player',
    displayName: 'Nova',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:06:00.000Z',
    connectionStatus: 'offline',
  },
  {
    id: 'player-7',
    userId: 'player-user-7',
    role: 'player',
    displayName: 'Toma',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:07:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-8',
    userId: 'player-user-8',
    role: 'player',
    displayName: 'Eli',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:08:00.000Z',
    connectionStatus: 'online',
  },
  {
    id: 'player-9',
    userId: 'player-user-9',
    role: 'player',
    displayName: 'Luna',
    avatarUrl: null,
    joinedAt: '2026-06-07T10:09:00.000Z',
    connectionStatus: 'online',
  },
];